### ISSUE TITLE
Implement kernel-level software timestamping

### ISSUE THREAD

**Issue by davidv1992** [memorysafety/ntpd-rs#14]
We need some way to have software timestamping work with tokio in a proper way. Would prefer to have thin unsafe wrappers for the system calls in separate crates, prefer also to have few dependencies (this shouldn't be too much code, and it is probably better to own it ourselves than have a dependency on something like nix, libc is acceptable though in my view)

**Comment by rnijveld** [comment]
I've been looking at a way to get this implemented.

Setting the right flags shouldn't be much trouble using the `RawFd` and a few basic libc calls, but reading the ancillary messages for the actual time stamp data is a bigger issue. Tokio doesn't implement it right now, although there have been some mentions (e.g. https://github.com/tokio-rs/tokio/issues/799). The most recent mention I could find (https://github.com/tokio-rs/tokio/issues/2975) suggests waiting for an std implementation (https://github.com/rust-lang/rust/issues/76915), but it looks like that will still take quite a lot of work to get somewhere.

I think our current best bet is to go with implementing our own `recvmsg` with [`AsyncFd`](https://docs.rs/tokio/latest/tokio/io/unix/struct.AsyncFd.html) to detect socket reading readiness. That would require us implementing our own parsing of ancillary control messages (for examples look at [std](https://github.com/rust-lang/rust/blob/master/library/std/src/os/unix/net/ancillary.rs) or the [recvmsg code in nix](https://github.com/nix-rust/nix/blob/c59a8c8cc6cc6922888d6f33635905f9ea3d3205/src/sys/socket/mod.rs#L1552)). That seems doable given our limited use-case, although it will require a good chunk of unsafe code because of all the pointer arithmetic involved.
