### ISSUE TITLE
Validation of Parsed Packets

### ISSUE THREAD

**Issue by davidv1992** [memorysafety/ntpd-rs#194]
Reported by jsha

In ntp-proto/src/packet.rs, there are some input fields that could be validated against [limits in the specification](https://datatracker.ietf.org/doc/html/rfc5905#section-7.2) but do not appear to be:

- Version should be 4
- Stratum should be less than or equal to MAXSTRAT
- Poll should be validated against MINPOLL and MAXPOLL

**Comment by davidv1992** [comment]
From how I understand the standard, the poll interval is not guaranteed to be set on packets in mode 4, so I think we should not be checking that.

**Comment by jsha** [comment]
https://datatracker.ietf.org/doc/html/rfc5905#page-54

>    The poll update routine is called when a valid packet is received and
   immediately after a poll message has been sent.  If in a burst, the
   poll interval is fixed at 2 s; otherwise, the host poll exponent
   hpoll is set to the minimum of ppoll from the last packet received
   and hpoll from the poll routine, but not less than MINPOLL or greater
   than MAXPOLL.

This doesn't explicitly say the poll interval will always have a value between MINPOLL and MAXPOLL, so I agree with you that this does not need to be validated at parse time.

I looked for implementation of the logic quoted above, and as far as I can tell it's not implemented. It looks like peer processing ignores the received `poll` field. The `Peer.remote_min_poll_interval` field is incremented based on RATE packets but does not appear to be affected by `poll` in received packets.

**Comment by davidv1992** [comment]
You are correct that we have overlooked to implement that section of the specification. However, after having dived into it I also am now of the opinion that we shouldn't. The spec as stated indicates that we should set the actual poll interval to the lowest of the last received poll interval from the server and our own desired poll interval. This seems like a bad idea as combined with the suggested implementation for fast_xmit this would result in us never being able to reduce the polling interval.

My best guess is that this is a mechanism that is needed for symmetric connections, where otherwise one of the two peers would not be able to get its desired polling interval, but as we don't implement these we should be fine without it.
